credentials:
  usernames:
    dcuapiaco:
      email: ginfreecss@mail.com
      name: gin freecss
      password: $2b$12$SXBakMdVFBsWPYTNx9i7w.uIHL9In9Om4gAi8BT0qnwA1C57I7o3i
cookie:
  expiry_days: 30
  key: JIJLzWvUhh
  name: binance_perpectual_futures_dashboard
preauthorized:
  emails:
  - ginfreecss@mail.com